const constants = {
    LOG_IN: 'LOG_IN',
    LOG_OUT: 'LOG_OUT',
    LOAD_ORGANIZATION: 'LOAD_ORGANIZATION',
    LOAD_BUDGET: 'LOAD_BUDGET',
    LOAD_BUDGET_ITEMS: 'LOAD_BUDGET_ITEMS',
    ADD_BUDGET_ITEM: 'ADD_BUDGET_ITEM',
    UPDATE_BUDGET_ITEM: 'UPDATE_BUDGET_ITEM'
};

export default constants;
