const constants = {
  LOG_IN: 'LOG_IN',
  LOG_OUT: 'LOG_OUT',
  LOAD_ORGANIZATION: 'LOAD_ORGANIZATION',
  LOAD_BUDGET: 'LOAD_BUDGET',
  LOAD_BUDGET_ITEMS: 'LOAD_BUDGET_ITEMS',
  ADD_BUDGET_ITEM: 'ADD_BUDGET_ITEM',
  UPDATE_BUDGET_ITEM: 'UPDATE_BUDGET_ITEM',
  REMOVE_BUDGET_ITEM: 'REMOVE_BUDGET_ITEM',
  SET_LANGUAGE: 'SET_LANGUAGE',
  UPDATE_TRANSLATIONS: 'UPDATE_TRANSLATIONS',
  LOAD_ORDERS: 'LOAD_ORDERS'
};

export default constants;
